version: 2.1

orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@4.7.0

setup: &setup
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts

# Define the jobs we want to run for this project
jobs:
  install:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: node-modules-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - .
  install_without_modules_cache:
    <<: *setup
    steps:
      - checkout
      - run: yarn
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - .
  lint:
    <<: *setup
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint
  tsc:
    <<: *setup
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn tsc
  e2e:
    executor: win/default
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: nvm install --lts
      - run: nvm use --lts
      - run: npm i -g @electron-forge/cli
      - run: cd packages/example; yarn package
      - run: cd packages/example; yarn e2e
  release:
    <<: *setup
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - run: mv packages/electron-state-ipc/package.json package.json && npx semantic-release
workflows:
  master_deploy:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - install
  develop_test:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - develop
                - release
                - hotfix
                - master
                - /renovate.*/
                - /custom-renovate.*/
      - lint:
          requires:
            - install
      - tsc:
          requires:
            - install
      - e2e:
          requires:
            - install
  renovate_verify:
    jobs:
      - install_without_modules_cache:
          filters:
            branches:
              only:
                - /renovate.*/
                - /custom-renovate.*/
      - lint:
          requires:
            - install_without_modules_cache
      - tsc:
          requires:
            - install_without_modules_cache
      - e2e:
          requires:
            - install_without_modules_cache
